# Generated by Django 6.0.7 on 2026-07-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('attempts', models.IntegerField(default=0)),
                ('solved', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('target', models.IntegerField()),
                ('progress', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('concepts', models.CharField(blank=True, max_length=500, null=True)),
                ('hints', models.TextField(blank=True, null=True)),
                ('comparison_mode', models.CharField(default='Exact', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SparkProfile',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('master', models.CharField(default='local[*]', max_length=100)),
                ('driver_memory', models.CharField(default='1g', max_length=20)),
                ('executor_memory', models.CharField(default='1g', max_length=20)),
                ('executor_cores', models.IntegerField(default=1)),
                ('shuffle_partitions', models.IntegerField(default=2)),
                ('adaptive_query_execution', models.BooleanField(default=True)),
                ('broadcast_threshold', models.IntegerField(default=10485760)),
                ('serializer', models.CharField(default='org.apache.spark.serializer.KryoSerializer', max_length=200)),
                ('default_parallelism', models.IntegerField(default=2)),
                ('extra_configs', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoadmap',
            fields=[
                ('level', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('opted_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_datasets', models.JSONField()),
                ('expected_output_dataset', models.CharField(max_length=100)),
                ('comparison_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='practice.problem')),
            ],
        ),
    ]
