# Generated by Django 6.0.7 on 2026-07-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='time_taken',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='companies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_icon', models.CharField(default='Award', max_length=50)),
                ('problems', models.ManyToManyField(related_name='challenges', to='practice.problem')),
            ],
        ),
    ]
