# Generated by Django 6.0.7 on 2026-07-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_goal_category_goal_completion_date_goal_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparkMasterTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('subtopics', models.JSONField(default=list)),
                ('points', models.IntegerField(default=10)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SparkMasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('focus_minutes_spent', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='practice.sparkmastertopic')),
            ],
        ),
    ]
